version: '3.8'

services:
  mysql_local:
    image: mysql/mysql-server:5.7.12
    logging:
      driver: none
    container_name: Union_local
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=defaultPassword
      - MYSQL_USER=dbAdmin
      - MYSQL_PASSWORD=defaultPassword
      - MYSQL_DATABASE=union_local
#    command: --default-authentication-plugin=mysql_native_password
    command:
      - mysqld
      - --sql_mode=NO_ENGINE_SUBSTITUTION
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --explicit_defaults_for_timestamp=ON
      - --server-id=2
    networks:
      - replica-docker

  adminer:
    image: adminer:4.8.1
    logging:
      driver: none
    restart: always
    ports:
      - 8080:8080
    networks:
      - replica-docker

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    networks:
      - replica-docker

volumes:
  mongodb_master_data:
    driver: local
  mongodb_arbiter_data:
    driver: local
  mongodb_secondary_data:
    driver: local

networks:
  replica-docker:
    driver: bridge



